version: "3"
services:
  mariadb:
    container_name: firefox_mariadb
    image: linuxserver/mariadb:10.6.13
    volumes:
      - ./dbdata:/config
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: syncstorage
      MYSQL_USER: sync
      MYSQL_PASSWORD: CHANGEMECHANGEME
      MYSQL_ROOT_PASSWORD: CHANGEMECHANGEME

  syncserver:
    container_name: firefox_syncserver
    build: ./syncstorage-rs-docker
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    environment:
      LOGLEVEL: info
      SYNC_URL: http://YOURHOSTNAME:8000 # Set this to the URL clients will connect to the sync server on
      SYNC_CAPACITY: 10 # Max number of users that will be accepted
      SYNC_MASTER_SECRET: CHANGEMECHANGEMECHANGEMECHANGEMECHANGEMECHANGEMECHANGEMECHANGEME # Use: cat /dev/urandom | base32 | head -c64
      METRICS_HASH_SECRET: CHANGEMECHANGEMECHANGEMECHANGEMECHANGEMECHANGEMECHANGEMECHANGEME # Use: cat /dev/urandom | base32 | head -c64
      SYNC_SYNCSTORAGE_DATABASE_URL: mysql://sync:CHANGEMECHANGEME@mariadb:3306/syncstorage_rs
      SYNC_TOKENSERVER_DATABASE_URL: mysql://sync:CHANGEMECHANGEME@mariadb:3306/tokenserver_rs
